language: java
dist: trusty

matrix:
  include:
    - jdk: openjdk8
      env: JDK=8
    - jdk: openjdk11
      env: JDK=11

script:
  - ./mvnw clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash)